### ISSUE TITLE
Dagher lab `proc_dash` integration roadmap

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/proc_dash#46]
- [x] #1
- [x] Sign up to demo current deployed dashboard at a Wednesday lab meeting (date TBD, would mostly likely be after May 17)
  - [x] Generate up-to-date PPMI and QPN bagels to use as sample inputs, if possible
- [x] #45 
- [x] In demo, describe integration with `mr_proc` as a workflow for enforcing organizational standards for an imaging dataset
- [ ] Suggest an afternoon hackathon with `mr_proc` team / brainstorm as part of demo how to help students organize their current data on the BIC/Compute Canada to be able to use the trackers + dashboard (not planned)
